name: build
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn analyze"
  test:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn ci:test"

  test_acceptance:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn ci:test:acc"
