name: build
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn analyze"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"
          cache: "yarn"
      - run: "yarn install"
      - run: "yarn test"
